# exampleSite/config.yaml
baseURL: https://v1m4c5.github.io/weblog/
languageCode: en-us
theme: smigle
themesDir: themes2 # Only needed for running the example site
title: Vimacs
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 4
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "Blog Author"
  brandIconFile: "images/img.svg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: Here
      url: https://v1m4c5.github.io
  subtitle: "Exploring the workd of text editing"
